import Image from "next/image";
import React from "react";
import Header from "./components/Header";
import NavSideBar from "./components/NavSideBar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const RootLayout = ({ children, params }) => {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen relative">
          {/* Sidebar */}
          <NavSideBar params={params} />

          {/* Main Content */}
          <div className="flex-1 relative overflow-hidden">
            {/* Header */}
            <Header />

            {/* Dashboard Content */}
            <div className="p-2 h-[93vh] overflow-x-auto flex justify-center items-start min-w-full">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
